config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'
  resources :restaurants, except: [:index, :edit, :update, :delete] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true
  # validates :rating, inclusion: 0..5
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'your restaurant was saved'
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1> Here is a list of the restaurants</h1>

  <% @restaurants.each do |restaurant| %>
<ul>
  <li>Name: <%= restaurant.name %> </li>
  <li>Address: <%=restaurant.address %> </li>
</ul>

  <% end %>

  <%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, :collection => %w[chinese italian japanese french belgian] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<p>
<%= link_to 'Return to restaurants', root_path %>
</p>

app/views/restaurants/show.html.erb
<h2> <%= @restaurant.name %></h2>

<p> This restaurant is located in
<%= @restaurant.address %>
</p>
<p> Contact details
<%= @restaurant.phone_number %>
</p>

<p> They serve <%= @restaurant.category %> food</p>

<p>Rstaurant reviews</p>

<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= "#{review.rating} - #{review.content}" %></li>
  <% end %>
</ul>


<p>Add your own review</p>

<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit 'Create a review' %>
<% end %>

<p>
<%= link_to 'Return to restaurants', root_path %>
</p>

app/views/reviews/new.html.erb
<%= simple_form for @review do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit %>

<% end %>